# Generated by Django 5.0.4 on 2024-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='auto_increment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='auto_increment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qrcodeupload',
            name='auto_increment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
